version: 2
jobs:
  tests:
    docker:
      - image: circleci/node:16.5.0

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
      - run: npm test
